version: 2.1

jobs:
  test_client:
    working_directory: ~/app-name
    docker:
      - image: circleci/node:11
    steps:
      - checkout

      - restore_cache:
          keys:
            - test_client-node-modules-{{ checksum "yarn.lock" }}
      - run: yarn install

      - save_cache:
          key: test_client-node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run: yarn test

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test_client
